# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45ab819c53153e0e04582a9c1295c5bca9bf3c837aba5b1d84a1c20dec1a6a89558840d0298db1d596f04a9414a681f1a868bf41d307daffe9799d4ddd6f8a7f

test:
  secret_key_base: cf921cd7ff35bf4e07f1fa2e989864fc5586edc86ce9a29eb8f74ecf5e76196b1864820c8662c3ca9cc3f280cc194f29b33e68f5e488bfc38345376c069791cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
