# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45ab819c53153e0e04582a9c1295c5bca9bf3c837aba5b1d84a1c20dec1a6a89558840d0298db1d596f04a9414a681f1a868bf41d307daffe9799d4ddd6f8a7f

# Google API keys
  google_access_token: "ya29.LgBsZL8C5Y2U1BoAAADNHeSNC0dWnmEZhp1QkCWT803e8hc9KKtbt1wvNHaiMA"
  google_authorization_uri: "https://accounts.google.com/o/oauth2/auth"
  google_client_id: "654060909251-1q1qbv5hcf1mndeijqs0k9s8rdtsjeps.apps.googleusercontent.com"
  google_client_secret: "UK5SM5-idw2Nqha_kQawFE5T"
  google_expires_in: 3600
  google_refresh_token: "1/-1fAoOYAHoiccAwW9YbLyUflt3-0z1DSfaiQH4q8UMc"
  google_token_credential_uri: "https://accounts.google.com/o/oauth2/token"
  google_issued_at: 1403126420 


test:
  secret_key_base: cf921cd7ff35bf4e07f1fa2e989864fc5586edc86ce9a29eb8f74ecf5e76196b1864820c8662c3ca9cc3f280cc194f29b33e68f5e488bfc38345376c069791cb

# TO_DO: Set OAUTH KEYS HERE
# "client_id":"654060909251-1q1qbv5hcf1mndeijqs0k9s8rdtsjeps.apps.googleusercontent.com",
# 	"client_secret":"UK5SM5-idw2Nqha_kQawFE5T",
  google_access_token: "ya29.LgBsZL8C5Y2U1BoAAADNHeSNC0dWnmEZhp1QkCWT803e8hc9KKtbt1wvNHaiMA"
  google_authorization_uri: "https://accounts.google.com/o/oauth2/auth"
  google_client_id: "654060909251-1q1qbv5hcf1mndeijqs0k9s8rdtsjeps.apps.googleusercontent.com"
  google_client_secret: "UK5SM5-idw2Nqha_kQawFE5T"
  google_expires_in: 3600
  google_refresh_token: "1/-1fAoOYAHoiccAwW9YbLyUflt3-0z1DSfaiQH4q8UMc"
  google_token_credential_uri: "https://accounts.google.com/o/oauth2/token"
  google_issued_at: 1403126420 

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 				<%= ENV["SECRET_KEY_BASE"] %>
  google_access_token: 			<%= ENV["GOOGLE_ACCESS_TOKEN"] %>
  google_authorization_uri: 	<%= ENV["GOOGLE_AUTHORIZATION_URI"] %>
  google_client_id: 			<%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: 		<%= ENV["GOOGLE_CLIENT_SECRET"] %>
  google_expires_in: 			<%= ENV["GOOGLE_EXPIRES_IN"] %>
  google_refresh_token: 		<%= ENV["GOOGLE_REFRESH_TOKEN"] %>
  google_token_credential_uri: 	<%= ENV["GOOGLE_TOKEN_CREDENTIAL_URI"] %>
  google_issued_at: 			<%= ENV["GOOGLE_ISSUED_AT"] %>
