class AddIndexes < ActiveRecord::Migration
  def change
  	add_index :events, :id
	add_index :events, :event_type_id
	add_index :events, :location_id
	add_index :events, :owner_id
	add_index :events, :g_cal_id
	add_index :events, :g_cal_event_id
	add_index :events, :organization_id
	add_index :event_groups, :id
	add_index :event_groups, :event_id
	add_index :event_groups, :group_id
	add_index :event_types, :id
	add_index :file_types, :id
	add_index :forms, :id
	add_index :forms, :organization_id
	add_index :form_fields, :id
	add_index :form_fields, :form_id
	add_index :form_submissions, :id
	add_index :form_submissions, :user_id
	add_index :form_submissions, :form_id
	add_index :form_submission_items, :id
	add_index :form_submission_items, :form_submission_id
	add_index :form_submission_items, :form_field_id
	add_index :groups, :id
	add_index :groups, :organization_id
	add_index :groups_payments, :id
	add_index :groups_payments, :group_id
	add_index :groups_payments, :payment_id
	add_index :groups_users, :id
	add_index :groups_users, :group_id
	add_index :groups_users, :user_id
	add_index :group_permissions, :id
	add_index :group_permissions, :group_id
	add_index :group_permissions, :permission_id
	add_index :g_cals, :id
	add_index :g_cals, :organization_id
	add_index :g_cals, :g_cal_id
	add_index :locations, :id
	add_index :locations, :organization_id
	add_index :organizations, :id
	add_index :organizations, :owner_id
	add_index :organizations, :org_type_id
	add_index :organizations, :parent_id
	add_index :organizations, :paypal_seller_id
	add_index :org_types, :id
	add_index :payments, :id
	add_index :payments, :owner_id
	add_index :payments, :organization_id
	add_index :payment_notifications, :id
	add_index :payment_notifications, :user_id
	add_index :payment_notifications, :transaction_id
	add_index :payment_notifications, :payment_id
	add_index :people, :id
	add_index :people, :user_id
	add_index :permissions, :id
	add_index :permissions, :action
	add_index :permissions, :organization_id
	add_index :permissions, :subject_class
	add_index :permissions, :action_scope
	add_index :responses, :id
	add_index :responses, :response_reason_id
	add_index :responses, :response_status_id
	add_index :responses, :event_id
	add_index :responses, :user_id
	add_index :responses, :review_status_id
	add_index :responses, :reviewed_user_id
	add_index :response_reasons, :id
	add_index :response_reasons, :organization_id
	add_index :response_statuses, :id
	add_index :review_statuses, :id
	add_index :uploads, :id
	add_index :uploads, :file_type_id
	add_index :uploads, :organization_id
	add_index :upload_groups, :id
	add_index :upload_groups, :upload_id
	add_index :upload_groups, :group_id
	add_index :users, :id
	add_index :users, :person_id
	add_index :users, :uid
  end
end
